import React from 'react';
import { mockImprovementGoals, mockActionableRoadmap } from '../data/mockImprovementPlan';
import { Card } from '../components/common/Card';
import { Badge } from '../components/common/Badge';
import { Button } from '../components/common/Button';
import { ProgressBar } from '../components/common/ProgressBar';
import {
  TrendingUp,
  CheckCircle2,
  AlertCircle,
  Target,
  Play,
  Calendar,
  Sparkles,
  ArrowRight,
  ShieldCheck,
} from 'lucide-react';
import { NavRoute } from '../components/layout/Sidebar';

interface ImprovementPlanPageProps {
  onStartDrill: (topic: string) => void;
  onNavigate: (route: NavRoute) => void;
}

export const ImprovementPlanPage: React.FC<ImprovementPlanPageProps> = ({
  onStartDrill,
  onNavigate,
}) => {
  return (
    <div className="space-y-8 pb-16 max-w-5xl mx-auto">
      {/* Header */}
      <div>
        <h1 className="text-2xl sm:text-3xl font-black font-display text-white flex items-center gap-2.5">
          <TrendingUp className="w-6 h-6 text-cyan-400" />
          Personalized Improvement Plan & Goals
        </h1>
        <p className="text-sm text-slate-400 mt-1">
          Dynamic action plan generated by MASTER AI based on your evaluated conversational and technical gaps.
        </p>
      </div>

      {/* ACTIVE GOALS SECTION */}
      <div className="space-y-4">
        <h2 className="text-lg font-bold font-display text-white flex items-center gap-2">
          <Target className="w-5 h-5 text-indigo-400" />
          Active Growth Objectives & Progress
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {mockImprovementGoals.map((goal) => (
            <Card
              key={goal.id}
              className="p-5 bg-[#0d1020]/90 border border-white/[0.08] backdrop-blur-xl flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs font-mono px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                    {goal.category.toUpperCase()}
                  </span>
                  <span className="text-xs font-mono font-bold text-cyan-400">
                    {goal.progressPercent}% Complete
                  </span>
                </div>

                <h3 className="text-base font-bold text-white mb-1.5">{goal.title}</h3>

                <div className="flex items-center justify-between text-xs font-mono text-slate-400 mb-3">
                  <span>Current: <strong className="text-slate-200">{goal.currentMetric}</strong></span>
                  <span>Target: <strong className="text-cyan-300">{goal.targetMetric}</strong></span>
                </div>

                <ProgressBar value={goal.progressPercent} variant="gradient" size="sm" className="mb-4" />

                <div className="space-y-2 mb-4">
                  <p className="text-[11px] font-mono text-slate-400 font-bold">RECOMMENDED ACTION ITEMS:</p>
                  {goal.actionItems.map((act, idx) => (
                    <div key={idx} className="flex items-start gap-2 text-xs text-slate-300">
                      <span className="text-cyan-400 font-bold shrink-0 mt-0.5">▸</span>
                      <span>{act}</span>
                    </div>
                  ))}
                </div>
              </div>

              <Button
                variant="outline"
                size="sm"
                rightIcon={<Play className="w-3 h-3 fill-current" />}
                onClick={() => onStartDrill(goal.title)}
                className="w-full mt-2 text-xs"
              >
                Launch Targeted Remediation Drill
              </Button>
            </Card>
          ))}
        </div>
      </div>

      {/* 4-WEEK ACTIONABLE ROADMAP */}
      <Card className="p-6 bg-[#0c0f1f]/90 border border-white/[0.08] backdrop-blur-xl space-y-4">
        <h2 className="text-base sm:text-lg font-bold font-display text-white flex items-center gap-2">
          <Calendar className="w-5 h-5 text-cyan-400" />
          4-Week Mastery Trajectory
        </h2>

        <div className="space-y-4 pt-2">
          {mockActionableRoadmap.map((item, idx) => {
            const isCompleted = item.status === 'completed';
            const isInProgress = item.status === 'in_progress';

            return (
              <div
                key={idx}
                className={`p-4 rounded-xl border ${
                  isInProgress
                    ? 'bg-indigo-950/40 border-indigo-400/50 shadow-md'
                    : isCompleted
                    ? 'bg-emerald-950/15 border-emerald-500/20 opacity-80'
                    : 'bg-slate-900/30 border-white/[0.04]'
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <h4 className="text-sm font-bold text-white flex items-center gap-2">
                    {item.phase}
                  </h4>
                  <Badge
                    variant={isCompleted ? 'emerald' : isInProgress ? 'cyan' : 'slate'}
                    size="sm"
                  >
                    {item.status.replace('_', ' ').toUpperCase()}
                  </Badge>
                </div>

                <div className="flex flex-wrap gap-2 mt-2">
                  {item.items.map((sub, sIdx) => (
                    <span
                      key={sIdx}
                      className="px-2.5 py-1 rounded-md bg-black/40 border border-white/10 text-xs text-slate-300 flex items-center gap-1.5"
                    >
                      <span className={isCompleted ? 'text-emerald-400' : 'text-cyan-400'}>
                        {isCompleted ? '✓' : '•'}
                      </span>
                      {sub}
                    </span>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </Card>
    </div>
  );
};
